data_args:
  dense_reward: true
  grid_size: 4
  grid_world_args:
    absorbing_state: false
    terminate_on_goal: false
  include_goal: false
  yield_every: null
data_path: grid_world/explore_then_exploit
